// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//
namespace Tomboy.Sharing {
    
    
    /// <remarks/>
    /// <remarks>
///Web Service providing access to Tomboy Notes
///</remarks>
    [System.Web.Services.WebServiceBinding(Name="TomboyWebServiceSoap", Namespace="http://beatniksoftware.com/tomboy/web/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoteInfo))]
    public class TomboyWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public TomboyWebService() {
            this.Url = "http://127.0.0.1:8088/tomboy/Tomboy.asmx";
        }
        
        /// <remarks>
///Allows a client to ping to make sure the Web Service is up and running
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://beatniksoftware.com/tomboy/web/Ping", RequestNamespace="http://beatniksoftware.com/tomboy/web/", ResponseNamespace="http://beatniksoftware.com/tomboy/web/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public void Ping() {
            this.Invoke("Ping", new object[0]);
        }
        
        public System.IAsyncResult BeginPing(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ping", new object[0], callback, asyncState);
        }
        
        public void EndPing(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks>
///Get the specified note
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://beatniksoftware.com/tomboy/web/GetNote", RequestNamespace="http://beatniksoftware.com/tomboy/web/", ResponseNamespace="http://beatniksoftware.com/tomboy/web/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public NoteFullInfo GetNote(string noteUri) {
            object[] results = this.Invoke("GetNote", new object[] {
                noteUri});
            return ((NoteFullInfo)(results[0]));
        }
        
        public System.IAsyncResult BeginGetNote(string noteUri, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNote", new object[] {
                noteUri}, callback, asyncState);
        }
        
        public NoteFullInfo EndGetNote(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((NoteFullInfo)(results[0]));
        }
        
        /// <remarks>
///Get all shared notes
///</remarks>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://beatniksoftware.com/tomboy/web/GetSharedNotes", RequestNamespace="http://beatniksoftware.com/tomboy/web/", ResponseNamespace="http://beatniksoftware.com/tomboy/web/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public NoteInfo[] GetSharedNotes() {
            object[] results = this.Invoke("GetSharedNotes", new object[0]);
            return ((NoteInfo[])(results[0]));
        }
        
        public System.IAsyncResult BeginGetSharedNotes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSharedNotes", new object[0], callback, asyncState);
        }
        
        public NoteInfo[] EndGetSharedNotes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((NoteInfo[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beatniksoftware.com/tomboy/web/")]
    public class NoteFullInfo : NoteInfo {
        
        /// <remarks/>
        public string XmlContent;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beatniksoftware.com/tomboy/web/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoteFullInfo))]
    public class NoteInfo {
        
        /// <remarks/>
        public string Guid;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string LastModified;
        
        /// <remarks/>
        public System.UInt32 Revision;
    }
}
